### ISSUE TITLE
Spinner instead of fade

### ISSUE THREAD

**Issue by tyteen4a03** [leafOfTree/svelte-lazy#1]
Is there a way to use a custom spinner image / component in place of a fade?

**Comment by leafOfTree** [comment]
Thanks for the suggestion. I've added a prop `placeholder`. You can use it like
```svelte
<Lazy height={300} placeholder={Loading} fadeOption={null}>
  <img alt="" src="https://picsum.photos/id/547/200/300" />
</Lazy>

<script>
  import Lazy from 'svelte-lazy';
  import Loading from './Loading.svelte';
</script>
```

**Comment by leafOfTree** [comment]
I probably didn't figure it out at first. But now with version `v1.0.0` the placeholder will be showing until the image `load` event triggers.

**Comment by leafOfTree** [comment]
I'm closing this issue. Feel free to reopen it if there is any problem.
