### ISSUE TITLE
Use it to lazy loading posts on scroll

### ISSUE THREAD

**Issue by RiccardoPP** [leafOfTree/svelte-lazy#15]
Hello, thanks for the plugin. It's possible to use it to create an  infinite scrolling homepage? For example , I have a list of posts fetched from a json file and I need to render them one after other in the index.svelte. Something like:

```
{#each posts as post}
		<Lazy>
			{@html post.content}
		</Lazy>
{/each}
```

Thanks.

**Comment by leafOfTree** [comment]
Hi, you need to specify the `height` prop for each node as close to the rendered content height as possible. So each node gets to know its approximate position in the list and render at the right time.

You can check the following which worked for me. BTW, you can update `svelte-lazy` first as I just did some fixes which may help.
```html
<script>
  import Lazy from 'svelte-lazy'

  const posts = [...Array(100).keys()].map(key => ({
    content: `<h1>Post${key}</h1>`
  }))
</script>

<section>
  {#each posts as post}
    <Lazy height={90}>
      {@html post.content}
    </Lazy>
  {/each}
</section>
```

**Comment by RiccardoPP** [comment]
Thanks.
