### ISSUE TITLE
Svelte Routify - Components don't load on page change.

### ISSUE THREAD

**Issue by doolijb** [leafOfTree/svelte-lazy#17]
Using Routify, components don't load on new pages until scroll has been triggered.

**Comment by doolijb** [comment]
**Routify2** - Current workaround on each page:
```js
import { afterPageLoad } from '@roxi/routify'
$afterPageLoad(() => document.dispatchEvent(new CustomEvent('scroll')))
```

**Comment by leafOfTree** [comment]
Hi, @doolijb. Thanks for your feedback. 

I did some investigation and found out that when changing pages, Routify probably removes the previous page dom and renders the new page dom simultaneously. It results in incorrect height from `node.getBoundingClientRect().top` for svelte-lazy not to load the component.

I simply added a timeout for initial loading checking. Please try the latest version `npm install svelte-lazy` and see if it works.

**Comment by doolijb** [comment]
Thanks for the quick response, I'll check tomorrow

**Comment by doolijb** [comment]
It's looking good in production with Firefox and Chrome, thanks a ton.
