### ISSUE TITLE
Sapper 500 Error

### ISSUE THREAD

**Issue by teds31** [leafOfTree/svelte-lazy#2]
This works very well but unfortunately, there is a brief second of a 500 error saying this is a not a valid SSR component. The page loads after the error comes up quickly but it is still noticeable.

**Comment by leafOfTree** [comment]
Hi, thanks for the feedback. I tried it and found that this issue occurs with sapper rollup template. 
https://github.com/sveltejs/sapper/issues/774 discussed a similar problem and shown that it can be solved by moving `svelte-lazy` to devDependencies:
```
npm i -D svelte-lazy
```
See https://github.com/sveltejs/sapper-template#using-external-components.

**Comment by teds31** [comment]
> Hi, thanks for the feedback. I tried it and found that this issue occurs with sapper rollup template.
> [sveltejs/sapper#774](https://github.com/sveltejs/sapper/issues/774) discussed a similar problem and shown that it can be solved by moving `svelte-lazy` to devDependencies:
> 
> ```
> npm i -D svelte-lazy
> ```
> 
> See https://github.com/sveltejs/sapper-template#using-external-components.

awesome fixed! i love this btw! more stars!

**Comment by leafOfTree** [comment]
I'm really glad to hear that!
