### ISSUE TITLE
Browser can be overloaded when user scrolls quickly trough long list

### ISSUE THREAD

**Issue by mkyral** [leafOfTree/svelte-lazy#25]
I'm working on an application that shows list of items. Each item is a complex component and it took some time to render. Also in list could be from several hundred to cca 5000 items. If user scrolls slowly or use filters to find specific items, all works correctly.

But when user scrolls quickly or drag scrollbar and move it quickly to the middle or end of the list, browser triggers generation of all items between start and final position. That could mean rendering of hundred or thousand items at once.  It can take several minutes and page stays blank till generation finish. User has to wait.

Would be nice to have a way, how to postpone rendering. E.g.: add a small delay and check again if item is still visible. If not, cancel rendering for this time. 

AS IS:
When user do a quick scroll, all items between start and final position are rendered, even most of items stays hidden.

TO BE:
When user do a quick scroll, only items, where he stops, are rendered.

**Comment by leafOfTree** [comment]
I added `unload` to those that scroll out of view, so now only those visible are rendered.
Please try the latest version https://www.npmjs.com/package/svelte-lazy and see if it works.

**Comment by mkyral** [comment]
Hi,
I did more tests and I find regression of #4. (https://github.com/leafOfTree/svelte-lazy/issues/4#issuecomment-1422333189 )

When items is shown on screen without scrolling (e.g. via filter), only "Loading…" text is shown, content is not loaded. I have to scroll or resize screen to force loading.

There is no v1.2.2 source code in repository, so I can't compare changes :-(

Could you check? 
Thanks

**Comment by leafOfTree** [comment]
Thanks, somehow I forgot to push the latest source code 🥲 .
Will check it and update the code.

**Comment by leafOfTree** [comment]
Updated. Please help verify v1.2.3.

**Comment by mkyral** [comment]
Sorry for delay. I can confirm that the fix works.
Thanks.

**Comment by leafOfTree** [comment]
Great, thanks.
