### ISSUE TITLE
Missing export warning on Vite

### ISSUE THREAD

**Issue by ohida** [leafOfTree/svelte-lazy#29]
Hi,
I encountered the following warning when compiling with Vite (5.0.10).

```
11:41:41 AM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-lazy@1.2.5

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

Thank you for your help :)

**Comment by leafOfTree** [comment]
Thanks. It has been fixed with version 1.2.7
