### ISSUE TITLE
Svelte 5.x support

### ISSUE THREAD

**Issue by bfontaine** [leafOfTree/svelte-lazy#38]
Hello,
Svelte 5 is stable since [last week](https://svelte.dev/blog/svelte-5-is-alive); do you plan to add support for it in the library in the near future?
Thanks.

**Comment by leafOfTree** [comment]
Thanks for sharing the news about svelte 5. 

I have updated svelte-lazy to support it. Also, svelte-lazy itself is migrated to svelte 5.

**Comment by bfontaine** [comment]
Thank you! :pray:

**Comment by leafOfTree** [comment]
I reverted svelte-lazy source code to svelte 4, as using svelte 5 in code will cause errors to users using 4.

Support for 5 continues.
```
  "peerDependencies": {
    "svelte": "^3.0.0 || ^4.0.0 || ^5.0.0"
  },
```
